name: Build to docs on master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build site to docs/
        run: npx vite build

      - name: Write CNAME file
        run: echo "gilabert-theo.fr" > docs/CNAME

      - name: Commit and push docs/
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs -f
          git commit -m "build: update site in docs/" || echo "No changes to commit"
          git push origin master
